= {project-name} Changelog
:project-name: PyRDP
:uri-repo: https://github.com/GoSecure/pyrdp
:uri-issue: {uri-repo}/issues/

This document provides a high-level view of the changes introduced in {project-name} by release.
For a detailed view of what has changed, refer to the {uri-repo}/commits/master[commit history] on GitHub.

== <master> - <unreleased>


== v1.2.0 - 2021-09-??

=== Security

* Backported security fixes from rdesktop to our Python C extension doing RLE processing.
  Exploitability wasn't verified. ({uri-issue}357[#357])

=== Enhancements

* `pyrdp-convert` video conversion is now 6x faster! (See {uri-issue}349[#349])
* `pyrdp-convert` video format can be viewed during encoding and will play even if the conversion process crashes or is halted ({uri-issue}352[#352], {uri-issue}353[#353])
* Better error reporting for `pyrdp-convert` ({uri-issue}361[#361])
* Minor CLI improvements
* Improved type hints
* Updated instructions to extract the RDP certificate and private key ({uri-issue}345[#345])
* Documentation updates ({uri-issue}335[#335], {uri-issue}339[#339], {uri-issue}340[#340], {uri-issue}360[#360])
* Replaced unmaintained dependency notify2 with py-notifier ({uri-issue}363[#363], {uri-issue}365[#365])

=== Bug fixes

* Fixed a memory leak in the bitmap decoding routine preventing the conversion or the replay of very large captures ({uri-issue}352[#352], {uri-issue}353[#353])
* Fixed `pyrdp-player` on macOS platforms ({uri-issue}362[#362])
* Fixed NLA redirection problems if original target and NLA redirection target are the same ({uri-issue}342[#342], {uri-issue}343[#343])
* Added a missing dependency for the GUI on Ubuntu 20.04 LTS ({uri-issue}348[#348], {uri-issue}351[#351], {uri-issue}355[#355])

=== Infrastructure

* The slim flavor of our Docker image is now provided for the ARM and ARM64 platforms ({uri-issue}346[#346])
* Docker images are now built and pushed via GitHub Actions ({uri-issue}334[#334], {uri-issue}341[#341])
* Added an automated video conversion test to CI configuration ({uri-issue}349[#349])


== v1.1.0 - 2021-08-05

Released just in time for our BlackHat USA Arsenal 2021 presentation! Here are
the high-level release highlights:

* Network-Level Authentication (NLA) redirection: if target is NLA redirect to a different non-NLA host
  (see this as a dynamic downgrade attack)
* Improved file collection capabilities: file deduplication, preserving client-side file hierarchies and preserve partial copies
* More reliable, powerful and faster `pyrdp-convert`
* Attempted credentials collection (NTLMSSP hashes in NLA context and plaintext otherwise)
* Improved logging in error conditions and general bug fixes

Full list of changes follows.

=== Breaking Changes

* `pyrdp-convert` command-line interface change: `--list` is now `--list-only` to better reflect what it does.
  The short form `-l` didn't change. ({uri-issue}311[#311])
* Log fields changes: `hash` is now `shasum` ({uri-issue}302[#302])

=== Enhancements

*Security*

* Cryptography dependency updated to 3.3.2 due to upstream security issues which we are not really concerned about for this project's use case
  (See {uri-issue}259[#259], {uri-issue}295[#295])
* Pillow dependency updated to 8.2.0 due to upstream security issues (see {uri-issue}306[#306] and {uri-issue}317[#317])
* rsa dependency updated to 4.7 due to upstream security issues (see {uri-issue}314[#314])

*Tools*

* `pyrdp-convert` now relies on scapy for session reconstruction from a pcap.
  This is more reliable and can handle multiple sessions at once.
  ({uri-issue}311[#311], {uri-issue}221[#221])
* `pyrdp-convert` MP4 conversion is now 2x faster! (See {uri-issue}234[#234] and {uri-issue}273[#273])
* Added a JSON output format to `pyrdp-convert` (See {uri-issue}236[#236])
* Use a proper progress bar with completion percentage and ETA in `pyrdp-convert` (See {uri-issue}274[#274])

*MITM*

* NLA Redirection: if the original destination server requires NLA we can now redirect the connection to a different destination server as specified by the `--nla-redirection-host` and `--nla-redirection-port` switches ({uri-issue}260[#260], {uri-issue}308[#308])
* Added NTLMSSP hash logging when NLA is used with NTLM as the authentication protocol.
  Hashes are logged to `pyrdp_output/logs/ntlmssp.log` in addition to stdout and JSON.
  (See {uri-issue}307[#307])
* Added _attempted_ credentials logging when using graphical login (non-NLA).
  It is using a heuristic of Enter being pressed or mouse being clicked in specific areas.
  (See {uri-issue}303[#303])
* PyRDP will log the value of the `HOST_IP` variable on start if it exists. You can set it to the IP address of the host running PyRDP. This is mostly helpful when you're using PyRDP in Docker and you want the IP of the Docker host in the logs.
* Added detection function for BlueKeep scans / exploit attempts. PyRDP will log the attempt and shut down the connection. The JSON log has an exploitInfo attribute as well as a parserInfo attribute to help investigate what happened.
* Added better logging for parser errors. PyRDP will now log which parser crashed and the data that was fed to that parser to make it crash. This makes it easier to investigate bugs and exploits. In JSON logs, this information shows up in the parserInfo attribute.
* Files intercepted or crawled by the MITM are now named according to the sha1 hash of their contents and stored in the `pyrdp_output/files` folder (see {uri-issue}261[#261])
* Files that are currently being downloaded by the MITM but are not complete are stored in the `pyrdp_output/files/tmp` folder
* Both the file stealer and the file crawler components now mimick the victim's filesystem by creating the same file hierarchy in the `pyrdp_output/filesystems/<SESSION_ID>` folders.
  Files in these folders are symbolic links to files in the `pyrdp_output/files` folder to avoid useless duplication.
  The symlinks are relative, which allows you to move the folder around without losing the mapping.
  (See {uri-issue}270[#270], {uri-issue}272[#272] and {uri-issue}299[#299])
* File interceptor will keep a copy of interrupted file transfers in `pyrdp_output/files/tmp/` and mention it in the logs ({uri-issue}333[#333])
* All JSON logs now have a `clientIp` field once a client IP address is known ({uri-issue}321[#321], {uri-issue}326[#326])
* Removed `mapping.json` file since all the information it would contain can be obtained by checking the `pyrdp_output/filesystems` folder
* Added tests for the DeviceRedirectionMITM and FileMapping classes ({uri-issue}268[#268])
* Added `clientPort` field to the message when a new client is connected ({uri-issue}310[#310])

=== Bug fixes

* Added SO_REUSEADDR to MITM socket to avoid having to wait for sockets stuck in `TIME_WAIT`
* Fixed a bug causing the connection to crash when the pointerCacheSize field is absent in PointerCapability (See {uri-issue}287[#287])
* Fixed a bug causing the connection to crash when the client sends no connection negotiation flags (See {uri-issue}283[#283])
* Fixed a bug preventing files opened by the RDPDR file stealer from being closed ({uri-issue}264[#264])
* Fixed an issue with ghost mouse pointers in replays converted to MP4 ({uri-issue}271[#271])
* Fixed a regression with the `--sensor-id` (`-s`) command line argument.
  It would not work since 1.0. ({uri-issue}279[#279])
* doc: README update to fix Windows install ({uri-issue}301[#301])
* Now handling space characters in password attempts ({uri-issue}303[#303])
* Fixed 'Too Many Files Open' situations ({uri-issue}265[#265], {uri-issue}309[#309])
* `core.ssl` JSON logs now properly carry the `commonName` and `certFile` variables ({uri-issue}326[#326])
* Fixed wrong date format string for sessions converted from a pcap ({uri-issue}330[#330], {uri-issue}332[#332])
* Fixed a crash when deleting active file transfers on a disconnect ({uri-issue}322[#322], {uri-issue}333[#333])

=== Infrastructure

* Add automated tests to CI configuration
* Fixed pip timeout issues when building full docker image on slow networks ({uri-issue}320[#320])
* Updated our dependencies to the latest stable versions for Docker builds ({uri-issue}327[#327])

=== Credits

Thanks to the following people who contributed to this release:

Alexandre Beaulieu (@alxbl), @dependabot[bot], @exys228, Francis Labelle (@xshill), Olivier Bilodeau (@obilodeau)


== 1.0.0 - 2020-10-19

We added many interesting features in the last couple of months and have used this tool in enough contexts to officially mark it as stable.
Some of the noteworthy features are described https://www.gosecure.net/blog/2020/10/20/announcing-pyrdp-1/[in our announcement blog post].

This release has a dedicated SecTor 2020 presentation: https://sector.ca/sessions/achieving-pyrdp-1-0-the-remote-desktop-pwnage-mitm-and-library/[Achieving PyRDP 1.0 – The Remote Desktop Pwnage MITM and Library].

=== Enhancements

*Tools*

* Introduced the `pyrdp-convert` tool to convert between pcaps, PyRDP replay files and MP4 video files.
  Read link:README.md#using-pyrdp-convert[its section in the README for details].
  See {uri-issue}199[#199], {uri-issue}188[#188] and {uri-issue}170[#170].

*Player*

* New `--headless` mode to output replay data to the terminal.
  All GUI dependencies are now optional enabling further Docker image size reduction.
  See {uri-issue}151[#151], {uri-issue}163[#163] and {uri-issue}190[#190].
* Added window scaling support for session replays ({uri-issue}101[#101], {uri-issue}208[#208])

*MITM*

* Added support for dynamic certificate cloning when no certificate is specified. ({uri-issue}94[#94], {uri-issue}243[#243]).
  This is enabled by default and can be overridden through the existing `-c` and `-k` arguments.
* File interception now saves files transferred via clipboard copy/paste ({uri-issue}100[#100])
* Added a transparent proxy mode where source or destination packets are unaltered from the client or the server's perspective.
  See link:docs/transparent-proxy.md[feature documentation for details and usage examples].
  See also {uri-issue}197[#197], {uri-issue}204[#204], {uri-issue}205[#205] and {uri-issue}239[#239].
* Added support for Network Level Authentication (NLA) by passing CredSSP authentication untouched.
  Activate it with the `--auth ssp` switch.
  It requires the RDP server's private key which must be given to PyRDP.
  See {uri-issue}229[#229] for details.
* Support for 32-bit x86 operating systems when not using the graphical interface ({uri-issue}150[#150])
* Added a `twistd` plugin ({uri-issue}174[#174], {uri-issue}177[#177], {uri-issue}191[#191])
* Loosen up TLS version checks to allow a broader set of clients and server ({uri-issue}192[#192], {uri-issue}193[#193])
* Explicitly disabled TLS 1.3 for now since we don't record TLS 1.3 master secrets yet ({uri-issue}116[#116], {uri-issue}193[#193])
* Logging can be customized using configuration files ({uri-issue}191[#191])
* Improvements on log correlation ({uri-issue}180[#180]):
  - Added `replayfilename` to the connection report log entry
  - Added `sessionID` to replay filename
* Added several switches to selectively disable features of PyRDP:
  - `--disable-active-clipboard` switch to prevent clipboard request injection
  - `--no-downgrade` switch to prevent protocol downgrading where possible {uri-issue}189[#189]
  - `--no-files` switch to prevent extracting transferred files {uri-issue}195[#195]
* Added support for the GDI graphics as the default graphics pipeline.
  The `--no-gdi` switch was added to force the previous behavior (bitmaps).
  See {uri-issue}50[#50] and {uri-issue}209[#209] for details.

=== Bug fixes

* Python 3.8 supported by fixing a logging.Formatter misuse ({uri-issue}176[#176])
* PyRDP no longer creates replay files for sessions with no activity ({uri-issue}169[#169], {uri-issue}207[#207])
* Fixed stack traces in the player when attempting to print strings ending with a null character ({uri-issue}182[#182])
* Removed NLA argument from `pyrdp-mitm`
* Updated and clarified documentation ({uri-issue}165[#165], {uri-issue}166[#166], {uri-issue}172[#172])

=== Infrastructure

* Docker images are now based on Ubuntu 20.04 ({uri-issue}251[#251])
* Docker image size reduced and split in default and `-slim` variants ({uri-issue}173[#173], {uri-issue}198[#198])
* Improved docker caching for faster development iterations ({uri-issue}217[#217], {uri-issue}219[#219])
* Changed default docker compose command now `pyrdp-mitm -h` to avoid confusing crash on `docker-compose up` ({uri-issue}173[#173])
* Added continuous integration with GitHub Actions that builds docker images and runs basic smoke tests ({uri-issue}194[#194], {uri-issue}201[#201], {uri-issue}202[#202], {uri-issue}253[#253])

=== Credits

Thanks to the following people who contributed to this release:

Olivier Bilodeau (@obilodeau), Alexandre Beaulieu (@alxbl), Émilio Gonzalez (@res260), Francis Labelle (@xshill), @robeving, @sotebob


== 0.4.1 - 2019-11-03

Now with 100% public docker image!

=== Enhancements

* Improvements to our docker image ({uri-issue}156[#156], {uri-issue}157[#157], {uri-issue}160[#160])
* Logging when Restricted Admin Mode is enabled on clients
* Documentation improvements

=== Bug fixes

* Fixed libGL.so.1 missing in docker image ({uri-issue}138[#138], {uri-issue}159[#159])

=== Release meta

* Released by: Olivier Bilodeau
* Release beer: Archibald's Triple Américaine limited edition from YUL Airport

=== Credits

Thanks to the following people who contributed to this release:

Émilio Gonzalez, Francis Labelle, Olivier Bilodeau, Ondrej Gersl


== 0.4.0 - 2019-09-01

Release just in time for our Derbycon talk!

=== Enhancements

* Add recursive folder download from the PyRDP Player and a queue to download files ({uri-issue}140[#140])
* Add file crawler to automatically download files from the client drive using pattern files ({uri-issue}141[#141])

=== Credits

Thanks to the following people who contributed to this release:

Maxime Carbonneau


== 0.3.0 - 2019-08-31

A special BlackHat USA Arsenal 2019 release!

* https://docs.google.com/presentation/d/17P_l2n-hgCehQ5eTWilru4IXXHnGIRTj4ftoW4BiX5A/edit?usp=sharing[BlackHat USA Arsenal 2019 slides]


=== Enhancements

* Added Windows support ({uri-issue}129[#129])
* Improved documentation for operation with Bettercap ({uri-issue}107[#107])
* Added a heuristics-based credential logger to enable credentials collection at scale ({uri-issue}106[#106])
* Dependency update: Replaced pycrypto with pycryptodome ({uri-issue}128[#128])
* UX improvements to the PyRDP-Player ({uri-issue}119[#119], {uri-issue}124[#124])
* Improved handling of X224 Negotiation Failures like NLA ({uri-issue}102[#102])
* Accept and log connections from scanners better ({uri-issue}136[#136])
* Added BlueKeep specific detection and logging ({uri-issue}114[#114])
* Added a log entry that summarizes a connection, useful to hunt specific connections ({uri-issue}117[#117])
* Logging minor improvements ({uri-issue}123[#123], {uri-issue}112[#112])


=== Bug fixes

* Added support for RDP v10.7 in the connection handshake ({uri-issue}135[#135])
* Fixed issue with `virtualenv` setup ({uri-issue}110[#110])
* Fixed connections to Windows servers with RDS enabled ({uri-issue}118[#118])
* Shared Folders: Fixed a case where DOSName had no nullbyte ({uri-issue}121[#121])


=== Credits

Thanks to the following people who contributed to this release:

Maxime Carbonneau, Émilio Gonzalez, Francis Labelle and Olivier Bilodeau



== 0.2.0 - 2019-05-15

A special _NorthSec 2019_ release just in time for
https://github.com/xshill[Francis Labelle] and
https://github.com/res260[Émilio Gonzalez]'s talk on {project-name}.

* https://docs.google.com/presentation/d/1avcn8Sh2b3IE7AA0G9l7Cj5F1pxqizUm98IbXUo2cvY/edit#slide=id.g404b70030f_0_581[Presentation Slides]
* https://youtu.be/5JztJzi-m48[Demo Video of a Session Takeover and more]
* https://youtu.be/bU67tj1RkMA[Demo Video of a cmd.exe payload triggered on connection]
* https://nsec.io/session/2019-welcome-to-the-jumble-improving-rdp-tooling-for-malware-analysis-and-pentesting.html[Abstract]

=== Enhancements

* Session takeover: take control of an active session with working mouse and keyboard
* Client-side file browsing and downloading
* Ability to run custom PowerShell or console commands on new connections (https://github.com/GoSecure/pyrdp#running-payloads-on-new-connections[documentation])
* Easier integration with `virtualenv` ({uri-issue}84[#84])
* Provided a simple Dockerfile for Docker image creation ({uri-issue}66[#66])
* Documentation on how to combine with Bettercap (more on the way)
* Important refactoring

=== Credits

Thanks to the following people who contributed to this release:

Etienne Lacroix, Olivier Bilodeau, Francis Labelle


== 0.1.0 - 2018-12-20

First release. See our
https://www.gosecure.net/blog/2018/12/19/rdp-man-in-the-middle-smile-youre-on-camera[introductory
blog post] for details.

=== Credits

Thanks to the following people who contributed to this release:

Francis Labelle, Émilio Gonzalez, CoolAcid

Special thanks to https://github.com/citronneur[Sylvain Peyrefitte] who
created RDPy on which we initially based PyRDP. We eventually had to fork due
to drastic changes in order to achieve the capabilities we were interested in
building. That said, his initial architecture and base library choices should
be recognized as they stood the test of time.
