= {project-name} Changelog
:project-name: PyRDP
:uri-repo: https://github.com/GoSecure/pyrdp
:uri-issue: {uri-repo}/issues/

This document provides a high-level view of the changes introduced in {project-name} by release.
For a detailed view of what has changed, refer to the {uri-repo}/commits/master[commit history] on GitHub.

== 0.3.0 - <releaseDate>

A special BlackHat USA Arsenal 2019 release!

* https://docs.google.com/presentation/d/17P_l2n-hgCehQ5eTWilru4IXXHnGIRTj4ftoW4BiX5A/edit?usp=sharing[BlackHat USA Arsenal 2019 slides]


=== Enhancements

* Added Windows support ({uri-issue}129[#129])
* Improved documentation for operation with Bettercap ({uri-issue}107[#107])
* Added a heuristics-based credential logger to enable credentials collection at scale ({uri-issue}106[#106])
* Dependency update: Replaced pycrypto with pycryptodome ({uri-issue}128[#128])
* UX improvements to the PyRDP-Player ({uri-issue}119[#119], {uri-issue}124[#124])
* Improved handling of X224 Negotiation Failures like NLA ({uri-issue}102[#102])
* Accept and log connections from scanners better ({uri-issue}136[#136])
* Added BlueKeep specific detection and logging ({uri-issue}114[#114])
* Added a log entry that summarizes a connection, useful to hunt specific connections ({uri-issue}117[#117])
* Logging minor improvements ({uri-issue}123[#123], {uri-issue}112[#112])


=== Bug fixes

* Added support for RDP v10.7 in the connection handshake ({uri-issue}135[#135])
* Fixed issue with `virtualenv` setup ({uri-issue}110[#110])
* Fixed connections to Windows servers with RDS enabled ({uri-issue}118[#118])
* Shared Folders: Fixed a case where DOSName had no nullbyte ({uri-issue}121[#121])


=== Credits

Thanks to the following people who contributed to this release:

Maxime Carbonneau, Émilio Gonzalez, Francis Labelle and Olivier Bilodeau


////
=== Release meta

* Released on:
* Released by:
* Release beer:
////


== 0.2.0 - 2019-05-15

A special _NorthSec 2019_ release just in time for
https://github.com/xshill[Francis Labelle] and
https://github.com/res260[Émilio Gonzalez]'s talk on {project-name}.

* https://docs.google.com/presentation/d/1avcn8Sh2b3IE7AA0G9l7Cj5F1pxqizUm98IbXUo2cvY/edit#slide=id.g404b70030f_0_581[Presentation Slides]
* https://youtu.be/5JztJzi-m48[Demo Video of a Session Takeover and more]
* https://youtu.be/bU67tj1RkMA[Demo Video of a cmd.exe payload triggered on connection]
* https://nsec.io/session/2019-welcome-to-the-jumble-improving-rdp-tooling-for-malware-analysis-and-pentesting.html[Abstract]

=== Enhancements

* Session takeover: take control of an active session with working mouse and keyboard
* Client-side file browsing and downloading
* Ability to run custom PowerShell or console commands on new connections (https://github.com/GoSecure/pyrdp#running-payloads-on-new-connections[documentation])
* Easier integration with `virtualenv` ({uri-issue}84[#84])
* Provided a simple Dockerfile for Docker image creation ({uri-issue}66[#66])
* Documentation on how to combine with Bettercap (more on the way)
* Important refactoring

=== Credits

Thanks to the following people who contributed to this release:

Etienne Lacroix, Olivier Bilodeau, Francis Labelle


== 0.1.0 - 2018-12-20

First release. See our
https://www.gosecure.net/blog/2018/12/19/rdp-man-in-the-middle-smile-youre-on-camera[introductory
blog post] for details.

=== Credits

Thanks to the following people who contributed to this release:

Francis Labelle, Émilio Gonzalez, CoolAcid

Special thanks to https://github.com/citronneur[Sylvain Peyrefitte] who
created RDPy on which we initially based PyRDP. We eventually had to fork due
to drastic changes in order to achieve the capabilities we were interested in
building. That said, his initial architecture and base library choices should
be recognized as they stood the test of time.
