= {project-name} Changelog
:project-name: PyRDP
:uri-repo: https://github.com/GoSecure/pyrdp
:uri-issue: {uri-repo}/issues/

This document provides a high-level view of the changes introduced in {project-name} by release.
For a detailed view of what has changed, refer to the {uri-repo}/commits/master[commit history] on GitHub.

== <master> - <unreleased>

=== Enhancements

* Added support for dynamic certificate cloning when no certificate is specified. ({uri-issue}94[#94])
* `pyrdp-mitm` now carves and saves files transferred via clipboard ({uri-issue}100[#100])
* Introduced the `pyrdp-convert` tool to convert between pcaps, PyRDP replay files and MP4 video files.
  Read link:README.md#using-pyrdp-convert[its section in the README for details].
  See {uri-issue}199[#199], {uri-issue}188[#188] and {uri-issue}170[#170].
* `pyrdp-player` can now run in headless mode (`--headless`).
  All GUI dependencies are now optional enabling further Docker image size reduction.
  See {uri-issue}151[#151], {uri-issue}163[#163] and {uri-issue}190[#190].
* `pyrdp-player` now support window scaling of the RDP session ({uri-issue}101[#101], {uri-issue}208[#208])
* Added support for the GDI graphics pipeline which is enabled by default.
  The `--no-gdi` switch was also added to disable GDI.
  See {uri-issue}50[#50] and {uri-issue}209[#209] for details.
* Added a transparent proxy mode where source or destination packets are unaltered from the client or the server's perspective.
  Read link:docs/transparent-proxy.md[the feature's documentation for setup and details.].
  Also see {uri-issue}197[#197], {uri-issue}204[#204] and {uri-issue}205[#205].
* Loosen up TLS version checks to allow a broader set of clients and server ({uri-issue}192[#192], {uri-issue}193[#193])
* Explicitly disabled TLS 1.3 for now since we don't (can't?) record TLS 1.3 master secrets yet ({uri-issue}116[#116], {uri-issue}193[#193])
* All logging can be customized using configuration files ({uri-issue}191[#191])
* Added `sessionID` to replay filename ({uri-issue}180[#180])
* Added `replayfilename` to the connection report log entry ({uri-issue}180[#180])
* Added a `twistd` plugin ({uri-issue}174[#174], {uri-issue}177[#177], {uri-issue}191[#191])
* Support for 32-bit x86 operating systems now that the GUI is optional ({uri-issue}150[#150])
* Documentation updates and fixes ({uri-issue}165[#165], {uri-issue}166[#166], {uri-issue}172[#172])
* Added `--disable-active-clipboard` switch to prevent clipboard request injection
* Added `--no-downgrade` switch to prevent protocol downgrading where possible {uri-issue}189[#189]
* Added `--no-files` switch to prevent extracting transferred files {uri-issue}195[#195]
* PyRDP no longer create replay files for garbage sessions with less than 19 bytes ({uri-issue}169[#169], {uri-issue}207[#207])

=== Bug fixes

* Python 3.8 supported by fixing a logging.Formatter misuse ({uri-issue}176[#176])
* Fixed stack traces in the player when attempting to print strings with ending null character ({uri-issue}182[#182])
* Remove NLA argument from `pyrdp-mitm`.
  It was never supported and thus misleading.

=== Infrastructure

* Docker image size reduced and split in default and `-slim` variants ({uri-issue}173[#173], {uri-issue}198[#198])
* Better use of Docker caching for faster development iterations ({uri-issue}217[#217], {uri-issue}219[#219])
* Default Docker Compose command now `pyrdp-mitm -h` to avoid confusing crash on `docker-compose up` ({uri-issue}173[#173])
* Added continuous integration leveraging GitHub Actions that builds the docker image and runs an integration test on both Ubuntu and Windows ({uri-issue}194[#194], {uri-issue}201[#201], {uri-issue}202[#202])


== 0.4.1 - 2019-11-03

Now with 100% public docker image!

=== Enhancements

* Improvements to our docker image ({uri-issue}156[#156], {uri-issue}157[#157], {uri-issue}160[#160])
* Logging when Restricted Admin Mode is enabled on clients
* Documentation improvements

=== Bug fixes

* Fixed libGL.so.1 missing in docker image ({uri-issue}138[#138], {uri-issue}159[#159])

=== Release meta

* Released by: Olivier Bilodeau
* Release beer: Archibald's Triple Américaine limited edition from YUL Airport

=== Credits

Thanks to the following people who contributed to this release:

Émilio Gonzalez, Francis Labelle, Olivier Bilodeau, Ondrej Gersl


== 0.4.0 - 2019-09-01

Release just in time for our Derbycon talk!

=== Enhancements

* Add recursive folder download from the PyRDP Player and a queue to download files ({uri-issue}140[#140])
* Add file crawler to automatically download files from the client drive using pattern files ({uri-issue}141[#141])

=== Credits

Thanks to the following people who contributed to this release:

Maxime Carbonneau


== 0.3.0 - 2019-08-31

A special BlackHat USA Arsenal 2019 release!

* https://docs.google.com/presentation/d/17P_l2n-hgCehQ5eTWilru4IXXHnGIRTj4ftoW4BiX5A/edit?usp=sharing[BlackHat USA Arsenal 2019 slides]


=== Enhancements

* Added Windows support ({uri-issue}129[#129])
* Improved documentation for operation with Bettercap ({uri-issue}107[#107])
* Added a heuristics-based credential logger to enable credentials collection at scale ({uri-issue}106[#106])
* Dependency update: Replaced pycrypto with pycryptodome ({uri-issue}128[#128])
* UX improvements to the PyRDP-Player ({uri-issue}119[#119], {uri-issue}124[#124])
* Improved handling of X224 Negotiation Failures like NLA ({uri-issue}102[#102])
* Accept and log connections from scanners better ({uri-issue}136[#136])
* Added BlueKeep specific detection and logging ({uri-issue}114[#114])
* Added a log entry that summarizes a connection, useful to hunt specific connections ({uri-issue}117[#117])
* Logging minor improvements ({uri-issue}123[#123], {uri-issue}112[#112])


=== Bug fixes

* Added support for RDP v10.7 in the connection handshake ({uri-issue}135[#135])
* Fixed issue with `virtualenv` setup ({uri-issue}110[#110])
* Fixed connections to Windows servers with RDS enabled ({uri-issue}118[#118])
* Shared Folders: Fixed a case where DOSName had no nullbyte ({uri-issue}121[#121])


=== Credits

Thanks to the following people who contributed to this release:

Maxime Carbonneau, Émilio Gonzalez, Francis Labelle and Olivier Bilodeau



== 0.2.0 - 2019-05-15

A special _NorthSec 2019_ release just in time for
https://github.com/xshill[Francis Labelle] and
https://github.com/res260[Émilio Gonzalez]'s talk on {project-name}.

* https://docs.google.com/presentation/d/1avcn8Sh2b3IE7AA0G9l7Cj5F1pxqizUm98IbXUo2cvY/edit#slide=id.g404b70030f_0_581[Presentation Slides]
* https://youtu.be/5JztJzi-m48[Demo Video of a Session Takeover and more]
* https://youtu.be/bU67tj1RkMA[Demo Video of a cmd.exe payload triggered on connection]
* https://nsec.io/session/2019-welcome-to-the-jumble-improving-rdp-tooling-for-malware-analysis-and-pentesting.html[Abstract]

=== Enhancements

* Session takeover: take control of an active session with working mouse and keyboard
* Client-side file browsing and downloading
* Ability to run custom PowerShell or console commands on new connections (https://github.com/GoSecure/pyrdp#running-payloads-on-new-connections[documentation])
* Easier integration with `virtualenv` ({uri-issue}84[#84])
* Provided a simple Dockerfile for Docker image creation ({uri-issue}66[#66])
* Documentation on how to combine with Bettercap (more on the way)
* Important refactoring

=== Credits

Thanks to the following people who contributed to this release:

Etienne Lacroix, Olivier Bilodeau, Francis Labelle


== 0.1.0 - 2018-12-20

First release. See our
https://www.gosecure.net/blog/2018/12/19/rdp-man-in-the-middle-smile-youre-on-camera[introductory
blog post] for details.

=== Credits

Thanks to the following people who contributed to this release:

Francis Labelle, Émilio Gonzalez, CoolAcid

Special thanks to https://github.com/citronneur[Sylvain Peyrefitte] who
created RDPy on which we initially based PyRDP. We eventually had to fork due
to drastic changes in order to achieve the capabilities we were interested in
building. That said, his initial architecture and base library choices should
be recognized as they stood the test of time.
