#
# This file is part of the PyRDP project.
# Copyright (C) 2021 GoSecure Inc.
# Licensed under the GPLv3 or later.
#

from enum import IntEnum

class NTLMSSPMessageType(IntEnum):
    NEGOTIATE_MESSAGE = 1
    CHALLENGE_MESSAGE = 2
    AUTHENTICATE_MESSAGE = 3

# 
class NTLMSSPChallengeType(IntEnum):
    PARSER_ASN_TAG  = 0xA0
    PARSER_ASN_ID   = 0xA1
    STATUS_ASN_ID   = 0xA0
    CREDSSP_VERSION = 0x05
    SEQUENCE_HEADER = 0x04
    # Negotiate Flags
    # https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/99d90ff4-957f-4c8a-80e4-5bfe5a9a9832
    NEGOTIATE_FLAGS = 0xE28A8215
    NEG_TOKEN_INIT_SEQ_MECH_MESSAGE_VERSION_HIGH = 0x05
    NEG_TOKEN_INIT_SEQ_MECH_MESSAGE_VERSION_LOW = 0x02
    NEG_TOKEN_INIT_SEQ_MECH_MESSAGE_VERSION_BUILT = 0x0ECE
    NEG_TOKEN_INIT_SEQ_MECH_MESSAGE_VERSION_RESERVED = 0x000000
    NEG_TOKEN_INIT_SEQ_MECH_MESSAGE_VERSION_NTLM_TYPE = 0x0F
    NTLMSSP_NTLM_CHALLENGE_AV_PAIRS_ID  = 0x0002
    NTLMSSP_NTLM_CHALLENGE_AV_PAIRS1_ID = 0x0001
    NTLMSSP_NTLM_CHALLENGE_AV_PAIRS2_ID = 0x0004
    NTLMSSP_NTLM_CHALLENGE_AV_PAIRS3_ID = 0x0003
    NTLMSSP_NTLM_CHALLENGE_AV_PAIRS5_ID = 0x0005
    NTLMSSP_NTLM_CHALLENGE_AV_PAIRS6_ID = 0x0000
